logo_dir: logos
channels:
    mezzo:
        plugin: onelike
        name: Mezzo
        page_url: http://onelike.tv/mezzo.html
        logo_url: http://onelike.tv/images/mezzo.png
    fashion-tv:
        plugin: onelike
        name: Fashion TV
        page_url: http://onelike.tv/fashion-tv.html
        logo_url: http://onelike.tv/images/fashion-tv.png
    nat-geo-wild:
        plugin: onelike
        name: Nat Geo Wild
        page_url: http://onelike.tv/nat-geo-wild.html
        logo_url: http://onelike.tv/images/nat-geo-wild.png
    evrokino:
        plugin: onelike
        name: Evrokino
        page_url: http://onelike.tv/evrokino.html
        logo_url: http://onelike.tv/images/evrokino.png
    national-geographic:
        plugin: onelike
        name: National Geographic
        page_url: http://onelike.tv/national-geographic.html
        logo_url: http://onelike.tv/images/natgeo.png
    viasat-nature:
        plugin: onelike
        name: Viasat Nature
        page_url: http://onelike.tv/viasat-nature.html
        logo_url: http://onelike.tv/images/via_nat.png
    vh1:
        plugin: onelike
        name: Vh1
        page_url: http://onelike.tv/vh1.html
        logo_url: http://onelike.tv/images/vh1.png
